# Generated by Django 2.2.7 on 2020-04-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoronaWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='origin',
            name='id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, unique=True),
        ),
    ]
